version: "3.3"

volumes:

  code: {}

services:

  nginx:
    container_name: gitpab-nginx
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /data/gitpab/nginx/ssl:/etc/ssl
      - code:/var/www/html
    ports:
      - 8000:80
      - 8443:443
    depends_on:
      - php
    restart: unless-stopped

  cron:
    container_name: gitpab-cron
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - code:/var/www/html
      - ./docker/cron/crontab:/etc/cron.d/app
    environment:
      GITLAB_PRIVATE_TOKEN: ${token}
      GITLAB_RESTRICTIONS_PROJECT_IDS: ${projects}
      GITLAB_HOST: ${host}
      APP_LOCALE: en
    links:
      - php
    restart: unless-stopped
    entrypoint: cron -f

  php:
    container_name: gitpab-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - code:/var/www/html
    environment:
      GITLAB_PRIVATE_TOKEN: ${token}
      GITLAB_RESTRICTIONS_PROJECT_IDS: ${projects}
      GITLAB_HOST: ${host}
      APP_LOCALE: en
    links:
      - db
    restart: unless-stopped

  db:
    container_name: gitpab-db
    image: postgres
    volumes:
      - /data/gitpab/postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: gitpab
      POSTGRES_USER: gitpab
      POSTGRES_PASSWORD: gitpab
    restart: unless-stopped
